apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
name: kind
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - hostPort: 8080
    containerPort: 8080
- role: worker
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraMounts:
  - hostPath: /
    containerPath: /mnt/root
  extraPortMappings:
  - hostPort: 30100
    containerPort: 30100
    protocol: TCP
  - hostPort: 30110
    containerPort: 30110
    protocol: TCP
  - hostPort: 30120
    containerPort: 30120
    protocol: TCP
  - hostPort: 30130
    containerPort: 30130
    protocol: TCP
  - hostPort: 30140
    containerPort: 30140
    protocol: TCP